
services:
  #Database Service
  postgres:
    image: postgres:18.1-alpine
    container_name: pern_auth_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-thispasswordneedstochange}
      POSTGRES_DB: ${DB_NAME:-pern_auth_postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-user} -d ${DB_NAME:-pern_auth_postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    container_name: pern_auth_server
    ports:
      - "${SERVER_PORT:-5000}:5000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://${DB_USER:-user}:${DB_PASSWORD:-thispasswordneedstochange}@postgres:5432/${DB_NAME:-pern_auth_postgres}
      SERVER_PORT: ${SERVER_PORT:-5000}
      JWT_SECRET: ${JWT_SECRET:-thisisasupersecretsecretkey}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./server:/app
      - /app/node_modules
    
    entrypoint: ["/app/docker-entrypoint.sh"]
    command: ["npm", "run", "dev"]

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5000/api/v1
    depends_on:
      - server
    stdin_open: true
    tty: true

volumes:
  postgres_data: